// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ToggleFinal from "./components/ToggleFinal.bs.js";

function App(Props) {
  var match = React.useState(function () {
        return true;
      });
  var setValue = match[1];
  var match$1 = React.useState(function () {
        return true;
      });
  var setValueOne = match$1[1];
  var match$2 = React.useState(function () {
        return true;
      });
  var setValueTwo = match$2[1];
  var match$3 = React.useState(function () {
        return true;
      });
  var setValueThree = match$3[1];
  return React.createElement(React.Fragment, undefined, React.createElement(ToggleFinal.make, {
                  value: match[0],
                  setValue: (function (param) {
                      return Curry._1(setValue, (function (prev) {
                                    return !prev;
                                  }));
                    })
                }), React.createElement("br", undefined), React.createElement(ToggleFinal.make, {
                  label: "short label",
                  value: match$1[0],
                  setValue: (function (param) {
                      return Curry._1(setValueOne, (function (prev) {
                                    return !prev;
                                  }));
                    }),
                  className: "size-small three-color-mode color-scheme-three"
                }), React.createElement("br", undefined), React.createElement(ToggleFinal.make, {
                  label: "this is a very long label",
                  value: match$2[0],
                  setValue: (function (param) {
                      return Curry._1(setValueTwo, (function (prev) {
                                    return !prev;
                                  }));
                    }),
                  className: "size-large two-color-mode color-scheme-two"
                }), React.createElement("br", undefined), React.createElement(ToggleFinal.make, {
                  value: match$3[0],
                  setValue: (function (param) {
                      return Curry._1(setValueThree, (function (prev) {
                                    return !prev;
                                  }));
                    }),
                  className: "color-scheme-one"
                }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
